
export enum ActionTypes {
  AUTH_EXTERNAL_POPUP = 'AUTH_EXTERNAL_POPUP',
  AUTH_UNSUCCESSFUL = 'AUTH_UNSUCCESSFUL',
  AUTH_SUCCESSFUL = 'AUTH_SUCCESSFUL',
  LOGOUT = 'LOGOUT',
  UPDATE_USER_NAME = 'UPDATE_USER_NAME',
}
